import type { FeedItemCardContent } from "./feed_item_card";

export const homeFeedItemContents: FeedItemCardContent[] = [
  { id: "feed-1", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-kitchen-noodles/720/1280", mediaAlt: "Mia Chen feed cover", nickname: "Mia Chen", description: "Tried this 10-min udon and now I am obsessed. #homecooking #weeknightdinner", avatarUrl: "https://i.pravatar.cc/128?img=11", musicTitle: "Late Night Kitchen - Mello", musicCoverUrl: "https://picsum.photos/seed/music-cover-kitchen-noodles/128/128", likeCount: 824500, commentCount: 12840, favoriteCount: 210200, shareCount: 8310 },
  { id: "feed-2", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-film-street/720/1280", mediaAlt: "Owen Frames feed cover", nickname: "Owen Frames", description: "Golden hour on 35mm. Which shot should I print? #filmphotography #street", avatarUrl: "https://i.pravatar.cc/128?img=32", musicTitle: "Soft Focus - Atlas", musicCoverUrl: "https://picsum.photos/seed/music-cover-film-street/128/128", likeCount: 1200300, commentCount: 24100, favoriteCount: 188400, shareCount: 9450 },
  { id: "feed-3", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-running-rain/720/1280", mediaAlt: "Nina Runs feed cover", nickname: "Nina Runs", description: "5k before work, rain included. Felt amazing after. #running #morningroutine", avatarUrl: "https://i.pravatar.cc/128?img=24", musicTitle: "On My Pace - Kairo", musicCoverUrl: "https://picsum.photos/seed/music-cover-running-rain/128/128", likeCount: 463200, commentCount: 8920, favoriteCount: 73900, shareCount: 2140 },
  { id: "feed-4", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-editing-desk/720/1280", mediaAlt: "Leo Studio feed cover", nickname: "LEO Studio", description: "Color grading this clip took forever but worth it. #editing #creatorlife", avatarUrl: "https://i.pravatar.cc/128?img=47", musicTitle: "Midnight Render - LEO", musicCoverUrl: "https://picsum.photos/seed/music-cover-editing-desk/128/128", likeCount: 697800, commentCount: 15300, favoriteCount: 98200, shareCount: 4210 },
  { id: "feed-5", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-dance-practice/720/1280", mediaAlt: "Sara Moves feed cover", nickname: "Sara Moves", description: "Beginner shuffle combo. Save this and try it tonight. #dancepractice #shuffle", avatarUrl: "https://i.pravatar.cc/128?img=59", musicTitle: "Feet First - Sara Moves", musicCoverUrl: "https://picsum.photos/seed/music-cover-dance-practice/128/128", likeCount: 1502000, commentCount: 40900, favoriteCount: 314600, shareCount: 19200 },
  { id: "feed-6", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-coffee-bar/720/1280", mediaAlt: "Jay Coffee feed cover", nickname: "Jay Coffee", description: "Dialed in a new Ethiopia roast this morning. #coffee #pourover", avatarUrl: "https://i.pravatar.cc/128?img=14", musicTitle: "Steam and Vinyl - Juno", musicCoverUrl: "https://picsum.photos/seed/music-cover-coffee-bar/128/128", likeCount: 356700, commentCount: 6920, favoriteCount: 88400, shareCount: 1750 },
  { id: "feed-7", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-winter-beach/720/1280", mediaAlt: "Ava Trips feed cover", nickname: "Ava Trips", description: "Small beach town in winter beats summer crowds. #travel #quietplaces", avatarUrl: "https://i.pravatar.cc/128?img=40", musicTitle: "Waves in December - Ava", musicCoverUrl: "https://picsum.photos/seed/music-cover-winter-beach/128/128", likeCount: 984300, commentCount: 18030, favoriteCount: 171900, shareCount: 6110 },
  { id: "feed-8", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-coding-night/720/1280", mediaAlt: "Derek Codes feed cover", nickname: "Derek Codes", description: "Tiny trick that made my UI feel 10x smoother. #frontend #webdev", avatarUrl: "https://i.pravatar.cc/128?img=8", musicTitle: "Keystrokes - Loop Dept.", musicCoverUrl: "https://picsum.photos/seed/music-cover-coding-night/128/128", likeCount: 542100, commentCount: 11220, favoriteCount: 129700, shareCount: 5380 },
  { id: "feed-9", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-home-workout/720/1280", mediaAlt: "Lina Fit feed cover", nickname: "Lina Fit", description: "No-equipment shoulder workout for busy days. #fitness #athome", avatarUrl: "https://i.pravatar.cc/128?img=22", musicTitle: "Push Day - Lina", musicCoverUrl: "https://picsum.photos/seed/music-cover-home-workout/128/128", likeCount: 913400, commentCount: 13510, favoriteCount: 206500, shareCount: 9020 },
  { id: "feed-10", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-balcony-plants/720/1280", mediaAlt: "Harry Garden feed cover", nickname: "Harry Garden", description: "My basil finally survived the week. Progress! #planttok #balconygarden", avatarUrl: "https://i.pravatar.cc/128?img=35", musicTitle: "Morning Water - Fern Club", musicCoverUrl: "https://picsum.photos/seed/music-cover-balcony-plants/128/128", likeCount: 289300, commentCount: 5340, favoriteCount: 64100, shareCount: 1290 },
  { id: "feed-11", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-blazer-looks/720/1280", mediaAlt: "Zoe Stylebook feed cover", nickname: "Zoe Stylebook", description: "3 outfits from one black blazer. Which one wins? #styling #minimalwardrobe", avatarUrl: "https://i.pravatar.cc/128?img=53", musicTitle: "Mirror Check - Zoe", musicCoverUrl: "https://picsum.photos/seed/music-cover-blazer-looks/128/128", likeCount: 1330700, commentCount: 31800, favoriteCount: 274000, shareCount: 11700 },
  { id: "feed-12", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-music-studio/720/1280", mediaAlt: "Ryan Beats feed cover", nickname: "Ryan Beats", description: "Built this beat from train station sounds. Headphones on. #producer #sampling", avatarUrl: "https://i.pravatar.cc/128?img=27", musicTitle: "Platform 3 - Ryan Beats", musicCoverUrl: "https://picsum.photos/seed/music-cover-music-studio/128/128", likeCount: 774600, commentCount: 16190, favoriteCount: 148300, shareCount: 6430 },
  { id: "feed-13", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-books-stack/720/1280", mediaAlt: "Ella Reads feed cover", nickname: "Ella Reads", description: "Books that got me out of a reading slump. #booktok #recommendations", avatarUrl: "https://i.pravatar.cc/128?img=64", musicTitle: "Turn the Page - Lumen", musicCoverUrl: "https://picsum.photos/seed/music-cover-books-stack/128/128", likeCount: 620900, commentCount: 14330, favoriteCount: 192700, shareCount: 3320 },
  { id: "feed-14", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-portrait-light/720/1280", mediaAlt: "Noah Shoot feed cover", nickname: "Noah Shoot", description: "POV: you found perfect window light at 4:27pm. #portrait #phototips", avatarUrl: "https://i.pravatar.cc/128?img=45", musicTitle: "Side Light - Noah", musicCoverUrl: "https://picsum.photos/seed/music-cover-portrait-light/128/128", likeCount: 858200, commentCount: 12740, favoriteCount: 119200, shareCount: 4880 },
  { id: "feed-15", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-logo-sketch/720/1280", mediaAlt: "Ivy Design feed cover", nickname: "Ivy Design", description: "Logo sketch to final mark in under 30 sec. #graphicdesign #process", avatarUrl: "https://i.pravatar.cc/128?img=19", musicTitle: "Vectors Only - Ivy", musicCoverUrl: "https://picsum.photos/seed/music-cover-logo-sketch/128/128", likeCount: 497500, commentCount: 10020, favoriteCount: 91300, shareCount: 2960 },
  { id: "feed-16", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-cinnamon-rolls/720/1280", mediaAlt: "Max Bakes feed cover", nickname: "Max Bakes", description: "Cinnamon roll layers came out perfect today. #baking #smallbatch", avatarUrl: "https://i.pravatar.cc/128?img=56", musicTitle: "Warm Oven - Max", musicCoverUrl: "https://picsum.photos/seed/music-cover-cinnamon-rolls/128/128", likeCount: 1094100, commentCount: 22790, favoriteCount: 245300, shareCount: 10540 },
  { id: "feed-17", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-skate-park/720/1280", mediaAlt: "Jules Skate feed cover", nickname: "Jules Skate", description: "Landed kickflip clean after 2 hours. Worth it. #skateboarding #progress", avatarUrl: "https://i.pravatar.cc/128?img=29", musicTitle: "Concrete Echo - Jules", musicCoverUrl: "https://picsum.photos/seed/music-cover-skate-park/128/128", likeCount: 701800, commentCount: 14910, favoriteCount: 102100, shareCount: 4680 },
  { id: "feed-18", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-desk-planner/720/1280", mediaAlt: "Emma Notes feed cover", nickname: "Emma Notes", description: "How I plan a productive week in 5 minutes. #studytok #planning", avatarUrl: "https://i.pravatar.cc/128?img=63", musicTitle: "Focus Mode - Emma", musicCoverUrl: "https://picsum.photos/seed/music-cover-desk-planner/128/128", likeCount: 934200, commentCount: 17100, favoriteCount: 223800, shareCount: 8830 },
  { id: "feed-19", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-mountain-fog/720/1280", mediaAlt: "Kai Hikes feed cover", nickname: "Kai Hikes", description: "Fog rolled in right before sunrise. Unreal view. #hiking #nature", avatarUrl: "https://i.pravatar.cc/128?img=37", musicTitle: "Trailhead - Kai", musicCoverUrl: "https://picsum.photos/seed/music-cover-mountain-fog/128/128", likeCount: 1412200, commentCount: 26500, favoriteCount: 289700, shareCount: 13210 },
  { id: "feed-20", mediaType: "image", mediaSrc: "https://picsum.photos/seed/video-cover-makeup-vanity/720/1280", mediaAlt: "Ruby Makeup feed cover", nickname: "Ruby Makeup", description: "Soft glam in 12 minutes, no filter. #makeuptutorial #grwm", avatarUrl: "https://i.pravatar.cc/128?img=51", musicTitle: "Glow Routine - Ruby", musicCoverUrl: "https://picsum.photos/seed/music-cover-makeup-vanity/128/128", likeCount: 1179800, commentCount: 28940, favoriteCount: 261400, shareCount: 10990 },
];
